[package]
name = "pangu-domain"
version = "0.1.0"
edition = "2021"

[lib]
name = "pangu_domain"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
